### ISSUE TITLE
DuckDB 1.2.0. release checklist

### ISSUE THREAD

**Issue by taniabogatsch** [marcboeker/go-duckdb#329]
This issue summarises a few points that must be addressed when updating to the latest duckdb version.

- [ ] Update the Windows build in the `Makefile`. As part of a bug fix, the `bundle-library` target changed slightly. Below are the updated steps.
- [ ] Decrease the binary file size. FreeBSD currently passes GitHub's 100MB limit. I need to try passing `LTO=thin` to `CXX_CMAKE_FLAGS`.
- [ ] Fix failing tests. For context, here is a list of expected test failures due to unsupported functionality:
   - https://github.com/marcboeker/go-duckdb/pull/324#discussion_r1873219293

```make
.PHONY: deps.windows.amd64
deps.windows.amd64: duckdb
	if [ "$(shell uname -s | tr '[:upper:]' '[:lower:]')" != "mingw64_nt-10.0-20348" ]; then echo "Error: must run build on windows"; false; fi
	mkdir -p deps/windows_amd64

	# Copied from the DuckDB repository and fixed for Windows. Ideally, `make bundle-library` should also work for Windows.
	cd duckdb && \
	${DUCKDB_COMMON_BUILD_FLAGS} GENERATOR="-G \"MinGW Makefiles\"" gmake release -j 2
	cd duckdb/build/release && \
		rm -rf bundle && \
		mkdir -p bundle && \
		cp src/libduckdb_static.a bundle/. && \
		cp third_party/*/libduckdb_*.a bundle/. && \
		cp extension/*/lib*_extension.a bundle/. && \
		cd bundle && \
		find . -name '*.a' -exec mkdir -p {}.objects \; -exec mv {} {}.objects \; && \
		find . -name '*.a' -execdir ${AR} -x {} \; && \
		${AR} cr ../libduckdb_bundle.a ./*/*.obj

	cp duckdb/build/release/libduckdb_bundle.a deps/windows_amd64/libduckdb.a
```

**Comment by jacques-n** [comment]
FYI I also proposed [using git lfs](https://github.com/marcboeker/go-duckdb/issues/336) to address the file size issue.

**Comment by taniabogatsch** [comment]
Yeah - we'll likely end up with LFS or a similar option. I tried `LTO=thin`, but that did not work. For freeBSD, I now use duckdb's `SMALLER_BINARY=1`, which reduces some of the less important templated code to decrease the binary size. 
I've been testing this here: https://github.com/taniabogatsch/go-duckdb/tree/build-latest.

**Comment by taniabogatsch** [comment]
Also linking https://github.com/marcboeker/go-duckdb/issues/336.

**Comment by taniabogatsch** [comment]
Closing this as the release steps have changed slightly; see discussions around file size, etc.
